# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pr:
  branches:
    include:
      - main

variables:
  azureSubscription: 's'
  imageRepository: 'assset-backend'
  appName: 'asset-be'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '0.0.1-dev'

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: ${REG_SERVICE}/$(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(REG_SERVICE)
    tags: |
      $(tag)

- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    containers: $(REG_SERVICE)/$(imageRepository):$(tag)